/** Стартовые примеры кода для «Начать с примера» и карточек пустого состояния. */
export const sampleCode: Record<string, string> = {
  javascript: [
    '// Пример: сумма корзины со скидкой',
    'const cart = [120, 250, 80];',
    'const total = cart.reduce((acc, price) => acc + price, 0);',
    "console.log('Итого со скидкой 10%:', total * 0.9);",
  ].join('\n'),
  typescript: [
    '// Пример: типы и сужение по полю kind',
    'interface User {',
    '  name: string;',
    '  age: number;',
    '}',
    '',
    'type Shape = { kind: "circle"; r: number } | { kind: "square"; size: number };',
    '',
    'const area = (s: Shape): number =>',
    '  s.kind === "circle" ? Math.PI * s.r ** 2 : s.size ** 2;',
    '',
    'const user: User = { name: "Аня", age: 25 };',
    'console.log(`${user.name}, ${user.age} лет`);',
    'console.log("Площадь круга:", area({ kind: "circle", r: 2 }).toFixed(2));',
  ].join('\n'),
  python: [
    '# Пример: числа Фибоначчи',
    'def fib(n):',
    '    a, b = 0, 1',
    '    for _ in range(n):',
    '        a, b = b, a + b',
    '    return a',
    '',
    'print([fib(i) for i in range(10)])',
  ].join('\n'),
  php: [
    '<?php',
    '// Пример: валидация email',
    "$email = 'user@example.com';",
    'var_dump(filter_var($email, FILTER_VALIDATE_EMAIL));',
  ].join('\n'),
  ruby: [
    '# Пример: обёртка с повторными запросами',
    '3.times do |attempt|',
    '  puts "Попытка #{attempt + 1}"',
    'end',
  ].join('\n'),
  java: [
    'public class Main {',
    '    public static void main(String[] args) {',
    '        System.out.println("Привет, Runit!");',
    '    }',
    '}',
  ].join('\n'),
  go: [
    '// Пример: срез и сумма значений',
    'package main',
    '',
    'import "fmt"',
    '',
    'func main() {',
    '\tprices := []int{120, 250, 80}',
    '\ttotal := 0',
    '\tfor _, price := range prices {',
    '\t\ttotal += price',
    '\t}',
    '\tfmt.Println("Итого:", total)',
    '}',
  ].join('\n'),
  cpp: [
    '// Пример: сумма чисел от 1 до 10',
    '#include <iostream>',
    '',
    'int main() {',
    '    int sum = 0;',
    '    for (int i = 1; i <= 10; ++i) {',
    '        sum += i;',
    '    }',
    '    std::cout << "Сумма 1..10 = " << sum << std::endl;',
    '    return 0;',
    '}',
  ].join('\n'),
  sql: [
    '-- Пример: таблица, вставка и выборка (SQLite, база в памяти)',
    'CREATE TABLE users (',
    '  id INTEGER PRIMARY KEY,',
    '  name TEXT NOT NULL,',
    '  age INTEGER',
    ');',
    '',
    "INSERT INTO users (name, age) VALUES ('Аня', 25), ('Борис', 31), ('Вера', 19);",
    '',
    'SELECT name, age FROM users WHERE age >= 20 ORDER BY age DESC;',
  ].join('\n'),
  bash: [
    '# Пример: приветствие и цикл по списку',
    'echo "Привет, Runit!"',
    '',
    'for lang in bash python sql; do',
    '  echo "Язык: $lang"',
    'done',
  ].join('\n'),
  html: [
    '<!doctype html>',
    '<html lang="ru">',
    '  <head>',
    '    <meta charset="utf-8" />',
    '    <style>',
    '      body {',
    '        margin: 0;',
    '        min-height: 100vh;',
    '        display: flex;',
    '        align-items: center;',
    '        justify-content: center;',
    '        font-family: system-ui, sans-serif;',
    '        background: linear-gradient(135deg, #2563eb, #7c3aed);',
    '      }',
    '      .card {',
    '        padding: 32px 40px;',
    '        border-radius: 16px;',
    '        background: #fff;',
    '        box-shadow: 0 12px 32px rgba(0, 0, 0, 0.2);',
    '        text-align: center;',
    '      }',
    '    </style>',
    '  </head>',
    '  <body>',
    '    <div class="card">',
    '      <h1>Привет, Runit!</h1>',
    '      <p>Меняйте разметку и стили — превью обновится.</p>',
    '    </div>',
    '  </body>',
    '</html>',
  ].join('\n'),
  css: [
    '/* Пример: стили для готовой разметки (.card, .title, .text, .list, .button) */',
    '.card {',
    '  max-width: 420px;',
    '  margin: 0 auto;',
    '  padding: 24px;',
    '  border-radius: 16px;',
    '  background: linear-gradient(135deg, #ffffff, #f1f5ff);',
    '  box-shadow: 0 10px 30px rgba(37, 99, 235, 0.18);',
    '}',
    '',
    '.title {',
    '  margin: 0 0 8px;',
    '  font-size: 24px;',
    '  color: #1e293b;',
    '}',
    '',
    '.text {',
    '  margin: 0 0 16px;',
    '  color: #475569;',
    '  line-height: 1.6;',
    '}',
    '',
    '.list {',
    '  display: flex;',
    '  gap: 8px;',
    '  padding: 0;',
    '  margin: 0 0 20px;',
    '  list-style: none;',
    '}',
    '',
    '.list li {',
    '  padding: 4px 10px;',
    '  border-radius: 999px;',
    '  font-size: 13px;',
    '  background: #e0e7ff;',
    '  color: #3730a3;',
    '}',
    '',
    '.button {',
    '  padding: 10px 20px;',
    '  border: none;',
    '  border-radius: 8px;',
    '  font-size: 15px;',
    '  color: #fff;',
    '  background: #2563eb;',
    '  cursor: pointer;',
    '  transition: background 0.2s;',
    '}',
    '',
    '.button:hover {',
    '  background: #1d4ed8;',
    '}',
  ].join('\n'),
};
